### ISSUE TITLE
Locale::Middleware never uses Accept-Language

### ISSUE THREAD

**Issue by sakuro** [ruby-gettext/locale#15]
locale 2.1.3

[Gist](https://gist.github.com/sakuro/c284b0bb738131cc639e428e95431ec8)

Locale::Middleware calls `Locale::Driver::CGI#set_request` with
`[request["lang"]]` as the first argument(`query_lang`).

https://github.com/ruby-gettext/locale/blob/b59486e6acfb76c2d8a6069f05b2690b8182e135/lib/locale/middleware.rb#L30-L33

It is `[nil]` when `lang` is not fed and it is added to `locales` as `Locale::Tag::Irregular: en`.  So `locales` _always_ becomes non-empty here and `unless locales.size > 0` clause prevents using values from `Accept-Language` header.

This applies to `lang` from both query string and cookie.

https://github.com/ruby-gettext/locale/blob/b59486e6acfb76c2d8a6069f05b2690b8182e135/lib/locale/driver/cgi.rb#L45-L60

**Comment by kou** [comment]
Good catch!

Do you want to open a PR for this? It seems that we can fix this by adding `.compact` to `[request["lang"]]` and `[request.cookies["lang"]]`.

**Comment by sakuro** [comment]
https://github.com/ruby-gettext/locale/pull/16
