### ISSUE TITLE
Should ignore LANGUAGE if locale is set to ‘C’

### ISSUE THREAD

**Issue by 375gnu** [ruby-gettext/locale#6]
According to https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html#The-LANGUAGE-variable

> Note: The variable LANGUAGE is ignored if the locale is set to ‘C’. In other words, you have to first enable localization, by setting LANG (or LC_ALL) to a value other than ‘C’, before you can use a language priority list through the LANGUAGE variable.

**Comment by 375gnu** [comment]
Please see https://github.com/375gnu/locale/commit/9caa0e0e5455853418d195c4730035b7fea25321

Does it satisfies you?

**Comment by kou** [comment]
> Does it satisfy you?

No.

Why does your change look `LC_MESSAGES`? The note you sited mentions only `LANG` and `LC_ALL`.

One more question. `LC_ALL=ja_JP LANG=C LANGUAGE=ja:fr ./XXX.rb` ignores `LANGUAGE` with your change. Is it expected? Should it be `(ENV["LC_ALL"] || ENV["LANG"]) == "C"`?

**Comment by 375gnu** [comment]
On 9/15/15, Kouhei Sutou <notifications@github.com> wrote:
>> Does it satisfy you?
>
> No.
>
> Why does your change look `LC_MESSAGES`? The note you sited mentions only
> `LANG` and `LC_ALL`.

Because actual locale value for language is controlled by LC_MESSAGES,
LANG and LC_ALL are the way to define it. And GNU gettext does the
same:

$ LANGUAGE='be_BY:be' LC_MESSAGES='C' gettext 'celestia' "About Celestia"
About Celestia


> One more question. `LC_ALL=ja_JP LANG=C LANGUAGE=ja:fr ./XXX.rb` ignores
> `LANGUAGE` with your change. Is it expected?

No. LC_ALL has higher priority.

> Should it be `(ENV["LC_ALL"] || ENV["LANG"]) == "C"`?

Maybe so:
return nil if (ENV["LC_ALL"]=='C' || ENV["LC_MESSAGES"]=='C') ||
(ENV["LANG"] == "C" && !ENV["LC_ALL"] && !ENV["LC_MESSAGES"])

**Comment by kou** [comment]
> Because actual locale value for language is controlled by LC_MESSAGES, LANG and LC_ALL are the way to define it. And GNU gettext does the same:
>
> ```text
> $ LANGUAGE='be_BY:be' LC_MESSAGES='C' gettext 'celestia' "About Celestia" About Celestia
> ```

Thanks. I understand.

Could you try the following patch? If it works as you expected, I'll commit and release a new version.

```diff
+++ b/lib/locale/driver/env.rb
@@ -57,6 +57,7 @@ module Locale
       # Gets the locales from environment variables. (LANGUAGE > LC_ALL > LC_MESSAGES > LANG)
       # * Returns: an Array of the locale as Locale::Tag::Posix or nil.
       def locales
+        return nil if (ENV["LC_ALL"] || ENV["LC_MESSAGES"] || ENV["LANG"]) == "C"
         locales = ENV["LANGUAGE"]
         if (locales != nil and locales.size > 0)
           locs = locales.split(/:/).collect{|v| Locale::Tag::Posix.parse(v)}.compact
```

**Comment by 375gnu** [comment]
On 9/15/15, Kouhei Sutou <notifications@github.com> wrote:

> Could you try the following patch? If it works as you expected, I'll commit
> and release a new version.

Locale::candidates returns only en, gettext returns original string.
So it seems to work.

**Comment by kou** [comment]
Thanks for confirming it.
I've released a new version.
